# Generated by Django 4.2.5 on 2023-09-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('from_agency', models.ManyToManyField(related_name='from_agency', to='agency.agency')),
                ('to_agency', models.ManyToManyField(related_name='to_agency', to='agency.agency')),
            ],
            options={
                'verbose_name_plural': 'requests',
            },
        ),
    ]
