# Generated by Django 4.2.5 on 2023-09-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_details', models.TextField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agency',
            name='location_coordinates',
        ),
        migrations.AddField(
            model_name='agency',
            name='location_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agency',
            name='location_long',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='CollaborationResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_details', models.TextField()),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('collaboration_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.collaborationrequest')),
                ('response_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
            ],
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='requesting_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='agency.agency'),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='target_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='agency.agency'),
        ),
    ]
