# Generated by Django 4.2.5 on 2023-09-26 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0009_room_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='chatRoom',
        ),
    ]
